/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.BuildingExecutive;

import com.mycompany.adminExecutive.adminExecComplaintManageFrame;
import com.mycompany.adminExecutive.adminExecutive;
import com.mycompany.adminExecutive.complaint;
import java.io.FileNotFoundException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jun Ming
 */
public class buildingExecEmployeeJobManageFrame extends javax.swing.JFrame {

    /**
     * Creates new form buildingExecManageEmployeeJob
     */
    public buildingExecEmployeeJobManageFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        JobDescTitle1 = new javax.swing.JLabel();
        employeeIdTitle1 = new javax.swing.JLabel();
        JobIdTitle1 = new javax.swing.JLabel();
        deleteBtn1 = new javax.swing.JButton();
        JobIdLabel1 = new javax.swing.JLabel();
        JobDescLabel1 = new javax.swing.JLabel();
        employeeIdLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        viewDetailBtn1 = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        JobDescTitle2 = new javax.swing.JLabel();
        employeeIdTitle2 = new javax.swing.JLabel();
        JobIdTitle2 = new javax.swing.JLabel();
        deleteBtn2 = new javax.swing.JButton();
        JobIdLabel2 = new javax.swing.JLabel();
        JobDescLabel2 = new javax.swing.JLabel();
        employeeIdLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        viewDetailBtn2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        JobDescTitle3 = new javax.swing.JLabel();
        employeeIdTitle3 = new javax.swing.JLabel();
        JobIdTitle3 = new javax.swing.JLabel();
        deleteBtn3 = new javax.swing.JButton();
        JobIdLabel3 = new javax.swing.JLabel();
        JobDescLabel3 = new javax.swing.JLabel();
        employeeIdLabel3 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        viewDetailBtn3 = new javax.swing.JButton();
        nextPage = new javax.swing.JButton();
        previousPage = new javax.swing.JButton();
        addNewJob = new javax.swing.JButton();
        jobSearchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        JobDescTitle1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JobDescTitle1.setForeground(new java.awt.Color(0, 0, 0));
        JobDescTitle1.setText("Job description");

        employeeIdTitle1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        employeeIdTitle1.setForeground(new java.awt.Color(0, 0, 0));
        employeeIdTitle1.setText("Employee Id");

        JobIdTitle1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JobIdTitle1.setForeground(new java.awt.Color(0, 0, 0));
        JobIdTitle1.setText("Job Id");
        JobIdTitle1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        deleteBtn1.setBackground(new java.awt.Color(204, 204, 204));
        deleteBtn1.setForeground(new java.awt.Color(0, 0, 0));
        deleteBtn1.setText("Delete");
        deleteBtn1.setBorder(null);
        deleteBtn1.setBorderPainted(false);
        deleteBtn1.setContentAreaFilled(false);
        deleteBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn1.setFocusPainted(false);
        deleteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn1ActionPerformed(evt);
            }
        });

        JobIdLabel1.setForeground(new java.awt.Color(0, 0, 0));
        JobIdLabel1.setText("jLabel4");

        JobDescLabel1.setForeground(new java.awt.Color(0, 0, 0));
        JobDescLabel1.setText("jLabel5");

        employeeIdLabel1.setForeground(new java.awt.Color(0, 0, 0));
        employeeIdLabel1.setText("jLabel6");

        viewDetailBtn1.setBackground(new java.awt.Color(204, 204, 204));
        viewDetailBtn1.setForeground(new java.awt.Color(0, 0, 0));
        viewDetailBtn1.setText("View Details");
        viewDetailBtn1.setBorder(null);
        viewDetailBtn1.setBorderPainted(false);
        viewDetailBtn1.setContentAreaFilled(false);
        viewDetailBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewDetailBtn1.setFocusPainted(false);
        viewDetailBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JobIdLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JobIdTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JobDescTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JobDescLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeIdTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeIdLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addComponent(viewDetailBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JobIdTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JobDescTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeIdTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JobDescLabel1)
                    .addComponent(JobIdLabel1)
                    .addComponent(employeeIdLabel1))
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(deleteBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(viewDetailBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setForeground(new java.awt.Color(0, 0, 0));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        JobDescTitle2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JobDescTitle2.setForeground(new java.awt.Color(0, 0, 0));
        JobDescTitle2.setText("Job description");

        employeeIdTitle2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        employeeIdTitle2.setForeground(new java.awt.Color(0, 0, 0));
        employeeIdTitle2.setText("Employee Id");

        JobIdTitle2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JobIdTitle2.setForeground(new java.awt.Color(0, 0, 0));
        JobIdTitle2.setText("Job Id");
        JobIdTitle2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        deleteBtn2.setBackground(new java.awt.Color(204, 204, 204));
        deleteBtn2.setForeground(new java.awt.Color(0, 0, 0));
        deleteBtn2.setText("Delete");
        deleteBtn2.setBorder(null);
        deleteBtn2.setBorderPainted(false);
        deleteBtn2.setContentAreaFilled(false);
        deleteBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn2.setFocusPainted(false);
        deleteBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn2ActionPerformed(evt);
            }
        });

        JobIdLabel2.setForeground(new java.awt.Color(0, 0, 0));
        JobIdLabel2.setText("jLabel4");

        JobDescLabel2.setForeground(new java.awt.Color(0, 0, 0));
        JobDescLabel2.setText("jLabel5");

        employeeIdLabel2.setForeground(new java.awt.Color(0, 0, 0));
        employeeIdLabel2.setText("jLabel6");

        viewDetailBtn2.setBackground(new java.awt.Color(204, 204, 204));
        viewDetailBtn2.setForeground(new java.awt.Color(0, 0, 0));
        viewDetailBtn2.setText("View Details");
        viewDetailBtn2.setBorder(null);
        viewDetailBtn2.setBorderPainted(false);
        viewDetailBtn2.setContentAreaFilled(false);
        viewDetailBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewDetailBtn2.setFocusPainted(false);
        viewDetailBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JobIdLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JobIdTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JobDescTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JobDescLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeIdTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeIdLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addComponent(viewDetailBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JobIdTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JobDescTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeIdTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JobDescLabel2)
                    .addComponent(JobIdLabel2)
                    .addComponent(employeeIdLabel2))
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(deleteBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(viewDetailBtn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setForeground(new java.awt.Color(0, 0, 0));

        JobDescTitle3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JobDescTitle3.setForeground(new java.awt.Color(0, 0, 0));
        JobDescTitle3.setText("Job description");

        employeeIdTitle3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        employeeIdTitle3.setForeground(new java.awt.Color(0, 0, 0));
        employeeIdTitle3.setText("Employee Id");

        JobIdTitle3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JobIdTitle3.setForeground(new java.awt.Color(0, 0, 0));
        JobIdTitle3.setText("Job Id");
        JobIdTitle3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        deleteBtn3.setBackground(new java.awt.Color(204, 204, 204));
        deleteBtn3.setForeground(new java.awt.Color(0, 0, 0));
        deleteBtn3.setText("Delete");
        deleteBtn3.setBorder(null);
        deleteBtn3.setBorderPainted(false);
        deleteBtn3.setContentAreaFilled(false);
        deleteBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn3.setFocusPainted(false);
        deleteBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn3ActionPerformed(evt);
            }
        });

        JobIdLabel3.setForeground(new java.awt.Color(0, 0, 0));
        JobIdLabel3.setText("jLabel4");

        JobDescLabel3.setForeground(new java.awt.Color(0, 0, 0));
        JobDescLabel3.setText("jLabel5");

        employeeIdLabel3.setForeground(new java.awt.Color(0, 0, 0));
        employeeIdLabel3.setText("jLabel6");

        viewDetailBtn3.setBackground(new java.awt.Color(204, 204, 204));
        viewDetailBtn3.setForeground(new java.awt.Color(0, 0, 0));
        viewDetailBtn3.setText("View Details");
        viewDetailBtn3.setBorder(null);
        viewDetailBtn3.setBorderPainted(false);
        viewDetailBtn3.setContentAreaFilled(false);
        viewDetailBtn3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewDetailBtn3.setFocusPainted(false);
        viewDetailBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailBtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JobIdLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JobIdTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JobDescTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JobDescLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeIdTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeIdLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addComponent(viewDetailBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JobIdTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JobDescTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeIdTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JobDescLabel3)
                    .addComponent(JobIdLabel3)
                    .addComponent(employeeIdLabel3))
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(deleteBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(viewDetailBtn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        nextPage.setBackground(new java.awt.Color(255, 255, 255));
        nextPage.setForeground(new java.awt.Color(0, 0, 0));
        nextPage.setText("Next");
        nextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPageActionPerformed(evt);
            }
        });

        previousPage.setBackground(new java.awt.Color(255, 255, 255));
        previousPage.setForeground(new java.awt.Color(0, 0, 0));
        previousPage.setText("Back");
        previousPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousPageActionPerformed(evt);
            }
        });

        addNewJob.setBackground(new java.awt.Color(255, 255, 255));
        addNewJob.setForeground(new java.awt.Color(0, 0, 0));
        addNewJob.setText("Add new");
        addNewJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewJobActionPerformed(evt);
            }
        });

        jobSearchTxt.setBackground(new java.awt.Color(255, 255, 255));
        jobSearchTxt.setForeground(new java.awt.Color(0, 0, 0));
        jobSearchTxt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jobSearchTxt.setCaretColor(new java.awt.Color(0, 0, 0));
        jobSearchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobSearchTxtActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(255, 255, 255));
        searchBtn.setForeground(new java.awt.Color(0, 0, 0));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(previousPage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(nextPage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jobSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(addNewJob, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jobSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchBtn))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addNewJob, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(previousPage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextPage, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn1ActionPerformed
        // TODO add your handling code here:
        if(!(JobIdLabel1.getText()).equals("no data")){
            deleteBtn(JobIdLabel1.getText());
        }else{
            JOptionPane.showMessageDialog(null, "This is an empty data", "Warning", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteBtn1ActionPerformed

    private void viewDetailBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailBtn1ActionPerformed
        // TODO add your handling code here:
        if(!(JobIdLabel1.getText()).equals("no data")){
            this.dispose();
            buildingExecEmployeeJobAddEditFrame employeeJobAddEdit = new buildingExecEmployeeJobAddEditFrame();
            employeeJobAddEdit.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            employeeJobAddEdit.pack();
            employeeJobAddEdit.setResizable(false);
            employeeJobAddEdit.setLocationRelativeTo(null);
            employeeJobAddEdit.setVisible(true);
            try {
                employeeJobAddEdit.addEditDetect("edit",JobIdLabel1.getText());
            } catch (FileNotFoundException ex) {
            }
        }else{
            JOptionPane.showMessageDialog(null, "This is an empty data", "Warning", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_viewDetailBtn1ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        buildingExecMenuFrame buildingMenu = new buildingExecMenuFrame();
        buildingMenu.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        buildingMenu.pack();
        buildingMenu.setResizable(false);
        buildingMenu.setLocationRelativeTo(null);
        buildingMenu.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void deleteBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn2ActionPerformed
        // TODO add your handling code here:
        if(!(JobIdLabel2.getText()).equals("no data")){
            deleteBtn(JobIdLabel2.getText());
        }else{
            JOptionPane.showMessageDialog(null, "This is an empty data", "Warning", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteBtn2ActionPerformed

    private void viewDetailBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailBtn2ActionPerformed
        // TODO add your handling code here:
        if(!(JobIdLabel2.getText()).equals("no data")){
            this.dispose();
            buildingExecEmployeeJobAddEditFrame employeeJobAddEdit = new buildingExecEmployeeJobAddEditFrame();
            employeeJobAddEdit.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            employeeJobAddEdit.pack();
            employeeJobAddEdit.setResizable(false);
            employeeJobAddEdit.setLocationRelativeTo(null);
            employeeJobAddEdit.setVisible(true);
            try {
                employeeJobAddEdit.addEditDetect("edit",JobIdLabel2.getText());
            } catch (FileNotFoundException ex) {
            }
        }else{
            JOptionPane.showMessageDialog(null, "This is an empty data", "Warning", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_viewDetailBtn2ActionPerformed

    private void deleteBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn3ActionPerformed
        // TODO add your handling code here:
        if(!(JobIdLabel3.getText()).equals("no data")){
            deleteBtn(JobIdLabel3.getText());
        }else{
            JOptionPane.showMessageDialog(null, "This is an empty data", "Warning", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_deleteBtn3ActionPerformed

    private void viewDetailBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailBtn3ActionPerformed
        // TODO add your handling code here:
        if(!(JobIdLabel3.getText()).equals("no data")){
            this.dispose();
            buildingExecEmployeeJobAddEditFrame employeeJobAddEdit = new buildingExecEmployeeJobAddEditFrame();
            employeeJobAddEdit.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            employeeJobAddEdit.pack();
            employeeJobAddEdit.setResizable(false);
            employeeJobAddEdit.setLocationRelativeTo(null);
            employeeJobAddEdit.setVisible(true);
            try {
                employeeJobAddEdit.addEditDetect("edit",JobIdLabel3.getText());
            } catch (FileNotFoundException ex) {
            }
        }else{
            JOptionPane.showMessageDialog(null, "This is an empty data", "Warning", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_viewDetailBtn3ActionPerformed

    private void nextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPageActionPerformed
        // TODO add your handling code here:
        previousPage.setEnabled(true);
        setEmployeeJobData();
    }//GEN-LAST:event_nextPageActionPerformed

    private void previousPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousPageActionPerformed
        // TODO add your handling code here:
        backButtonFunction();
        setEmployeeJobData();
        nextPage.setEnabled(true);
    }//GEN-LAST:event_previousPageActionPerformed

    private void addNewJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewJobActionPerformed
        // TODO add your handling code here:
        this.dispose();
        buildingExecEmployeeJobAddEditFrame employeeJobAddEdit = new buildingExecEmployeeJobAddEditFrame();
        employeeJobAddEdit.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        employeeJobAddEdit.pack();
        employeeJobAddEdit.setResizable(false);
        employeeJobAddEdit.setLocationRelativeTo(null);
        employeeJobAddEdit.setVisible(true);
        try {
            employeeJobAddEdit.addEditDetect("add","");
        } catch (FileNotFoundException ex) {
        }
    }//GEN-LAST:event_addNewJobActionPerformed

    private void jobSearchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobSearchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobSearchTxtActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        this.searchTxt = jobSearchTxt.getText();
        this.PageLine=-1;
        previousPage.setEnabled(false);
        nextPage.setEnabled(true);
        setEmployeeJobData();
    }//GEN-LAST:event_searchBtnActionPerformed

     private Integer PageLine=-1;
    
    public void setPagination(){
        PageLine=PageLine+1;
    }
    
    private String searchTxt ="";
    
    public void backButtonToggle(){
        previousPage.setEnabled(false);
}
    
    public void backButtonFunction(){
        PageLine = PageLine -6;
        if (PageLine==-1){
            previousPage.setEnabled(false);
        }
    }
    
    public void setEmployeeJobData(){
        employeeJob employeeJobClass = new employeeJob();
        setPagination();
        employeeJobClass.displayDataView(PageLine,searchTxt,"EmployeeJob");
        boolean boo = employeeJobClass.getStatus();
        if(boo==false){
            nextPage.setEnabled(false);
        }
        if(employeeJobClass.getJobId() !=null){
            JobIdLabel1.setText(employeeJobClass.getJobId());
            JobDescLabel1.setText(employeeJobClass.getEmployeeJob());
            employeeIdLabel1.setText(employeeJobClass.getEmployeeId());
        }else{
            JobIdLabel1.setText("no data");
            JobDescLabel1.setText("no data");
            employeeIdLabel1.setText("no data");
        }
        setPagination();
        employeeJobClass.displayDataView(PageLine,searchTxt,"EmployeeJob");
        boo = employeeJobClass.getStatus();
        if(boo==false){
            nextPage.setEnabled(false);
        }
        if(employeeJobClass.getJobId() !=null){
            JobIdLabel2.setText(employeeJobClass.getJobId());
            JobDescLabel2.setText(employeeJobClass.getEmployeeJob());
            employeeIdLabel2.setText(employeeJobClass.getEmployeeId());
        }else{
            JobIdLabel2.setText("no data");
            JobDescLabel2.setText("no data");
            employeeIdLabel2.setText("no data");
        }
        setPagination();
        employeeJobClass.displayDataView(PageLine,searchTxt,"EmployeeJob");
        boo = employeeJobClass.getStatus();
        if(boo==false){
            nextPage.setEnabled(false);
        }
        if(employeeJobClass.getJobId() !=null){
            JobIdLabel3.setText(employeeJobClass.getJobId());
            JobDescLabel3.setText(employeeJobClass.getEmployeeJob());
            employeeIdLabel3.setText(employeeJobClass.getEmployeeId());
        }else{
            JobIdLabel3.setText("no data");
            JobDescLabel3.setText("no data");
            employeeIdLabel3.setText("no data");
        }
    }
    
    //Method for delete button, so no need to be repetitive
    public void deleteBtn(String getText){
        if(!getText.equals("no data")){
            int ques = JOptionPane.showConfirmDialog(null,"confirm to delete this data", "Quit", JOptionPane.YES_NO_OPTION);
            if (ques == JOptionPane.YES_OPTION){
                buildingExecutive main = new buildingExecutive();
                main.chooseTxtFile("EmployeeJob");
                buildingExecutive.buildingExecutiveMethod mainInner = main.new buildingExecutiveMethod();
                mainInner.deleteEmployeeJob(getText);
                JOptionPane.showMessageDialog(null, "Deleted Successfully", "Message", JOptionPane.INFORMATION_MESSAGE);
                
                this.dispose();
                buildingExecEmployeeJobManageFrame buildingEmployeeJob = new buildingExecEmployeeJobManageFrame();
                buildingEmployeeJob.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                buildingEmployeeJob.pack();
                buildingEmployeeJob.setResizable(false);
                buildingEmployeeJob.setLocationRelativeTo(null);
                buildingEmployeeJob.setVisible(true);
                buildingEmployeeJob.backButtonToggle();
                //Run Method in BusManUserManage to set UserType and Data
                buildingEmployeeJob.setEmployeeJobData();
            }
        }else{
            JOptionPane.showMessageDialog(null, "This is an empty data", "Warning", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buildingExecEmployeeJobManageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buildingExecEmployeeJobManageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buildingExecEmployeeJobManageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buildingExecEmployeeJobManageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buildingExecEmployeeJobManageFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JobDescLabel1;
    private javax.swing.JLabel JobDescLabel2;
    private javax.swing.JLabel JobDescLabel3;
    private javax.swing.JLabel JobDescTitle1;
    private javax.swing.JLabel JobDescTitle2;
    private javax.swing.JLabel JobDescTitle3;
    private javax.swing.JLabel JobIdLabel1;
    private javax.swing.JLabel JobIdLabel2;
    private javax.swing.JLabel JobIdLabel3;
    private javax.swing.JLabel JobIdTitle1;
    private javax.swing.JLabel JobIdTitle2;
    private javax.swing.JLabel JobIdTitle3;
    private javax.swing.JButton addNewJob;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteBtn1;
    private javax.swing.JButton deleteBtn2;
    private javax.swing.JButton deleteBtn3;
    private javax.swing.JLabel employeeIdLabel1;
    private javax.swing.JLabel employeeIdLabel2;
    private javax.swing.JLabel employeeIdLabel3;
    private javax.swing.JLabel employeeIdTitle1;
    private javax.swing.JLabel employeeIdTitle2;
    private javax.swing.JLabel employeeIdTitle3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jobSearchTxt;
    private javax.swing.JButton nextPage;
    private javax.swing.JButton previousPage;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton viewDetailBtn1;
    private javax.swing.JButton viewDetailBtn2;
    private javax.swing.JButton viewDetailBtn3;
    // End of variables declaration//GEN-END:variables
}
