/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class FacilityBooking extends javax.swing.JFrame {

    ResidentMain residentMain;
    String residentId;
    public ArrayList<String> dataList;
    
    public FacilityBooking() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        residentMain = new ResidentMain();
        displayData();
        backPageBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        topLabel = new javax.swing.JLabel();
        editBtn1 = new javax.swing.JButton();
        backPageBtn = new javax.swing.JButton();
        nextPageBtn = new javax.swing.JButton();
        facilityIdLabel1 = new javax.swing.JLabel();
        facilityIdTxt1 = new javax.swing.JLabel();
        facilityNameLabel1 = new javax.swing.JLabel();
        bookDateLabel1 = new javax.swing.JLabel();
        facilityNameTxt1 = new javax.swing.JLabel();
        bookDateTxt1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bookTimeLabel1 = new javax.swing.JLabel();
        bookTimeTxt1 = new javax.swing.JLabel();
        bookDurationLabel1 = new javax.swing.JLabel();
        bookDurationTxt1 = new javax.swing.JLabel();
        deleteBtn1 = new javax.swing.JButton();
        facilityIdLabel2 = new javax.swing.JLabel();
        facilityIdTxt2 = new javax.swing.JLabel();
        facilityNameLabel2 = new javax.swing.JLabel();
        facilityNameTxt2 = new javax.swing.JLabel();
        bookDateLabel2 = new javax.swing.JLabel();
        bookDateTxt2 = new javax.swing.JLabel();
        bookTimeLabel2 = new javax.swing.JLabel();
        bookTimeTxt2 = new javax.swing.JLabel();
        bookDurationLabel2 = new javax.swing.JLabel();
        bookDurationTxt2 = new javax.swing.JLabel();
        editBtn2 = new javax.swing.JButton();
        deleteBtn2 = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(233, 233, 233));
        jPanel1.setPreferredSize(new java.awt.Dimension(566, 600));

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setForeground(new java.awt.Color(0, 0, 0));
        backBtn.setText("Back");
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        topLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        topLabel.setForeground(new java.awt.Color(0, 0, 0));
        topLabel.setText("FACILITY BOOKING");

        editBtn1.setBackground(new java.awt.Color(255, 255, 255));
        editBtn1.setForeground(new java.awt.Color(0, 0, 0));
        editBtn1.setText("EDIT");
        editBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtn1ActionPerformed(evt);
            }
        });

        backPageBtn.setBackground(new java.awt.Color(255, 255, 255));
        backPageBtn.setForeground(new java.awt.Color(0, 0, 0));
        backPageBtn.setText("Back");
        backPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backPageBtnActionPerformed(evt);
            }
        });

        nextPageBtn.setBackground(new java.awt.Color(255, 255, 255));
        nextPageBtn.setForeground(new java.awt.Color(0, 0, 0));
        nextPageBtn.setText("Next");
        nextPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPageBtnActionPerformed(evt);
            }
        });

        facilityIdLabel1.setBackground(new java.awt.Color(233, 233, 233));
        facilityIdLabel1.setForeground(new java.awt.Color(0, 0, 0));
        facilityIdLabel1.setText("Facility ID :");

        facilityIdTxt1.setBackground(new java.awt.Color(233, 233, 233));
        facilityIdTxt1.setForeground(new java.awt.Color(0, 0, 0));
        facilityIdTxt1.setText("F1");

        facilityNameLabel1.setBackground(new java.awt.Color(233, 233, 233));
        facilityNameLabel1.setForeground(new java.awt.Color(0, 0, 0));
        facilityNameLabel1.setText("Facility Name :");

        bookDateLabel1.setBackground(new java.awt.Color(233, 233, 233));
        bookDateLabel1.setForeground(new java.awt.Color(0, 0, 0));
        bookDateLabel1.setText("Booking Date :");

        facilityNameTxt1.setBackground(new java.awt.Color(233, 233, 233));
        facilityNameTxt1.setForeground(new java.awt.Color(0, 0, 0));
        facilityNameTxt1.setText("badminton court 1");

        bookDateTxt1.setBackground(new java.awt.Color(233, 233, 233));
        bookDateTxt1.setForeground(new java.awt.Color(0, 0, 0));
        bookDateTxt1.setText("01-01-2023");

        bookTimeLabel1.setBackground(new java.awt.Color(233, 233, 233));
        bookTimeLabel1.setForeground(new java.awt.Color(0, 0, 0));
        bookTimeLabel1.setText("Booking Time :");

        bookTimeTxt1.setBackground(new java.awt.Color(233, 233, 233));
        bookTimeTxt1.setForeground(new java.awt.Color(0, 0, 0));
        bookTimeTxt1.setText("16.00-19.00");

        bookDurationLabel1.setBackground(new java.awt.Color(233, 233, 233));
        bookDurationLabel1.setForeground(new java.awt.Color(0, 0, 0));
        bookDurationLabel1.setText("Booking Duration :");

        bookDurationTxt1.setBackground(new java.awt.Color(233, 233, 233));
        bookDurationTxt1.setForeground(new java.awt.Color(0, 0, 0));
        bookDurationTxt1.setText("3 hours 30 minutes");

        deleteBtn1.setBackground(new java.awt.Color(255, 255, 255));
        deleteBtn1.setForeground(new java.awt.Color(0, 0, 0));
        deleteBtn1.setText("DELETE");
        deleteBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn1ActionPerformed(evt);
            }
        });

        facilityIdLabel2.setBackground(new java.awt.Color(233, 233, 233));
        facilityIdLabel2.setForeground(new java.awt.Color(0, 0, 0));
        facilityIdLabel2.setText("Facility ID :");

        facilityIdTxt2.setBackground(new java.awt.Color(233, 233, 233));
        facilityIdTxt2.setForeground(new java.awt.Color(0, 0, 0));
        facilityIdTxt2.setText("F1");

        facilityNameLabel2.setBackground(new java.awt.Color(233, 233, 233));
        facilityNameLabel2.setForeground(new java.awt.Color(0, 0, 0));
        facilityNameLabel2.setText("Facility Name :");

        facilityNameTxt2.setBackground(new java.awt.Color(233, 233, 233));
        facilityNameTxt2.setForeground(new java.awt.Color(0, 0, 0));
        facilityNameTxt2.setText("badminton court 1");

        bookDateLabel2.setBackground(new java.awt.Color(233, 233, 233));
        bookDateLabel2.setForeground(new java.awt.Color(0, 0, 0));
        bookDateLabel2.setText("Booking Date :");

        bookDateTxt2.setBackground(new java.awt.Color(233, 233, 233));
        bookDateTxt2.setForeground(new java.awt.Color(0, 0, 0));
        bookDateTxt2.setText("01-01-2023");

        bookTimeLabel2.setBackground(new java.awt.Color(233, 233, 233));
        bookTimeLabel2.setForeground(new java.awt.Color(0, 0, 0));
        bookTimeLabel2.setText("Booking Time :");

        bookTimeTxt2.setBackground(new java.awt.Color(233, 233, 233));
        bookTimeTxt2.setForeground(new java.awt.Color(0, 0, 0));
        bookTimeTxt2.setText("16.00-19.00");

        bookDurationLabel2.setBackground(new java.awt.Color(233, 233, 233));
        bookDurationLabel2.setForeground(new java.awt.Color(0, 0, 0));
        bookDurationLabel2.setText("Booking Duration :");

        bookDurationTxt2.setBackground(new java.awt.Color(233, 233, 233));
        bookDurationTxt2.setForeground(new java.awt.Color(0, 0, 0));
        bookDurationTxt2.setText("3 hours 30 minutes");

        editBtn2.setBackground(new java.awt.Color(255, 255, 255));
        editBtn2.setForeground(new java.awt.Color(0, 0, 0));
        editBtn2.setText("EDIT");
        editBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtn2ActionPerformed(evt);
            }
        });

        deleteBtn2.setBackground(new java.awt.Color(255, 255, 255));
        deleteBtn2.setForeground(new java.awt.Color(0, 0, 0));
        deleteBtn2.setText("DELETE");
        deleteBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn2ActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 0, 0));
        addBtn.setText("ADD");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(facilityIdLabel2)
                            .addComponent(facilityNameLabel2)
                            .addComponent(bookDateLabel2)
                            .addComponent(bookTimeLabel2)
                            .addComponent(bookDurationLabel2)
                            .addComponent(editBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bookDurationTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(facilityNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(facilityIdTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bookDateTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(bookTimeTxt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(deleteBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(topLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(backPageBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextPageBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(facilityNameLabel1)
                            .addComponent(facilityIdLabel1)
                            .addComponent(bookDateLabel1)
                            .addComponent(bookTimeLabel1)
                            .addComponent(bookDurationLabel1)
                            .addComponent(editBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(bookTimeTxt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(deleteBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(facilityNameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookDateTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facilityIdTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookDurationTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(backPageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextPageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(topLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facilityIdLabel1)
                    .addComponent(facilityIdTxt1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facilityNameLabel1)
                    .addComponent(facilityNameTxt1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookDateLabel1)
                    .addComponent(bookDateTxt1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookTimeLabel1)
                    .addComponent(bookTimeTxt1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookDurationLabel1)
                    .addComponent(bookDurationTxt1))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facilityIdLabel2)
                    .addComponent(facilityIdTxt2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(facilityNameTxt2)
                    .addComponent(facilityNameLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookDateLabel2)
                    .addComponent(bookDateTxt2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookTimeLabel2)
                    .addComponent(bookTimeTxt2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bookDurationLabel2)
                    .addComponent(bookDurationTxt2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn1ActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Click 'YES' Will Delete Selected Booking ",
            "WARNING", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION)
        {
            removeSelected("upper");
            this.dispose();
            ResidentPay residentPay = new ResidentPay();
            residentPay.setVisible(true);
        }
    }//GEN-LAST:event_deleteBtn1ActionPerformed

    private void nextPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPageBtnActionPerformed

        backPageBtn.setEnabled(true);
        displayData();
    }//GEN-LAST:event_nextPageBtnActionPerformed

    private void backPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backPageBtnActionPerformed

        backButtonFunction();
        nextPageBtn.setEnabled(true);
        displayData();
    }//GEN-LAST:event_backPageBtnActionPerformed

    private void editBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtn1ActionPerformed
        this.dispose();
        dataList = new ArrayList<String>();
        dataList.add(facilityIdTxt1.getText());
        dataList.add(facilityNameTxt1.getText());
        dataList.add(bookDateTxt1.getText());
        dataList.add(bookTimeTxt1.getText());
        dataList.add(bookDurationTxt1.getText());
        FacilityBookingAddEdit facilityBookingAddEdit = new FacilityBookingAddEdit("edit", dataList );
        facilityBookingAddEdit.setVisible(true);
    }//GEN-LAST:event_editBtn1ActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        ResidentOption residentOption = new ResidentOption();
        residentOption.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void editBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtn2ActionPerformed
        this.dispose();
        dataList = new ArrayList<String>();
        dataList.add(facilityIdTxt2.getText());
        dataList.add(facilityNameTxt2.getText());
        dataList.add(bookDateTxt2.getText());
        dataList.add(bookTimeTxt2.getText());
        dataList.add(bookDurationTxt2.getText());
        FacilityBookingAddEdit facilityBookingAddEdit = new FacilityBookingAddEdit("edit", dataList );
        facilityBookingAddEdit.setVisible(true);
    }//GEN-LAST:event_editBtn2ActionPerformed

    private void deleteBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn2ActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Click 'YES' Will Delete Selected Booking ",
            "WARNING", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION)
        {
            removeSelected("bottom");
            this.dispose();
            ResidentPay residentPay = new ResidentPay();
            residentPay.setVisible(true);
        }
    }//GEN-LAST:event_deleteBtn2ActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacilityBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacilityBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacilityBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacilityBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacilityBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backPageBtn;
    private javax.swing.JLabel bookDateLabel1;
    private javax.swing.JLabel bookDateLabel2;
    private javax.swing.JLabel bookDateTxt1;
    private javax.swing.JLabel bookDateTxt2;
    private javax.swing.JLabel bookDurationLabel1;
    private javax.swing.JLabel bookDurationLabel2;
    private javax.swing.JLabel bookDurationTxt1;
    private javax.swing.JLabel bookDurationTxt2;
    private javax.swing.JLabel bookTimeLabel1;
    private javax.swing.JLabel bookTimeLabel2;
    private javax.swing.JLabel bookTimeTxt1;
    private javax.swing.JLabel bookTimeTxt2;
    private javax.swing.JButton deleteBtn1;
    private javax.swing.JButton deleteBtn2;
    private javax.swing.JButton editBtn1;
    private javax.swing.JButton editBtn2;
    private javax.swing.JLabel facilityIdLabel1;
    private javax.swing.JLabel facilityIdLabel2;
    private javax.swing.JLabel facilityIdTxt1;
    private javax.swing.JLabel facilityIdTxt2;
    private javax.swing.JLabel facilityNameLabel1;
    private javax.swing.JLabel facilityNameLabel2;
    private javax.swing.JLabel facilityNameTxt1;
    private javax.swing.JLabel facilityNameTxt2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton nextPageBtn;
    private javax.swing.JLabel topLabel;
    // End of variables declaration//GEN-END:variables

    private int pageLine=-1;
    
    private void setPagination(){
        pageLine=pageLine+1;
    }
    
    public void backButtonFunction(){
        pageLine = pageLine - 4;
        if (pageLine == -1){
            backPageBtn.setEnabled(false);
        }
    }
    
    private void displayData(){
        setPagination();
        displayDataView(pageLine, "upper");
        boolean boo = residentMain.getStatus();
        if(boo==false){
            nextPageBtn.setEnabled(false);
        }
        
        setPagination();
        displayDataView(pageLine, "bottom");
        boolean boo2 = residentMain.getStatus();
        if(boo2==false){
            nextPageBtn.setEnabled(false);
        }
        
    }
    
    private void displayDataView(Integer pageLine, String part)
    {
        try{
            String bookingFile = "src/main/java/com/mycompany/textFile/FacilityBooking.txt";
            ArrayList<ArrayList<String>> userData = onlyUserDataInfo(bookingFile);
            int newSize = userData.size();            
            try{
                userData.get(pageLine);
                if(part.equals("upper"))
                {
                    facilityIdTxt1.setText(userData.get(pageLine).get(2));
                    facilityNameTxt1.setText(userData.get(pageLine).get(3));
                    bookDateTxt1.setText(userData.get(pageLine).get(5));
                    bookTimeTxt1.setText(userData.get(pageLine).get(6));
                    bookDurationTxt1.setText(userData.get(pageLine).get(7));
                    facilityIdTxt2.setText("no data");
                    facilityNameTxt2.setText("no data");
                    bookDateTxt2.setText("no data");
                    bookTimeTxt2.setText("no data");
                    bookDurationTxt2.setText("no data");
                    editBtn2.setEnabled(false);
                    deleteBtn2.setEnabled(false);
                    residentMain.setStatus(true);
                }else{
                    facilityIdTxt2.setText(userData.get(pageLine).get(2));
                    facilityNameTxt2.setText(userData.get(pageLine).get(3));
                    bookDateTxt2.setText(userData.get(pageLine).get(5));
                    bookTimeTxt2.setText(userData.get(pageLine).get(6));
                    bookDurationTxt2.setText(userData.get(pageLine).get(7));
                    residentMain.setStatus(true);
                }
                if(facilityIdTxt1.getText() == null)
                {
                    facilityIdTxt1.setText("no data");
                    facilityNameTxt1.setText("no data");
                    bookDateTxt1.setText("no data");
                    bookTimeTxt1.setText("no data");
                    bookDurationTxt1.setText("no data");
                }
                if(facilityIdTxt2.getText() == null)
                {
                    facilityIdTxt2.setText("no data");
                    facilityNameTxt2.setText("no data");
                    bookDateTxt2.setText("no data");
                    bookTimeTxt2.setText("no data");
                    bookDurationTxt2.setText("no data");
                }
                
            }
            catch (Exception ex) {
                residentMain.setStatus(false);
            }
            
            if(pageLine.equals(newSize-1)){
                residentMain.setStatus(false);
            }
        }
        catch(FileNotFoundException ex){
            Logger.getLogger(ResidentPay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
    private ArrayList<ArrayList<String>> onlyUserDataInfo(String textFile) throws FileNotFoundException 
    {
        ArrayList<ArrayList<String>> allUserInfo = allUserDataInfo(textFile);
        ArrayList<ArrayList<String>> onlyUserInfo = new ArrayList<>();
        
        
        int p,q;
        for (p=0,q=0; p<allUserInfo.size(); p++)
        {
            if(allUserInfo.get(p).contains(residentId))
            {
                ArrayList<String> item = allUserInfo.get(p);
                if(item.get(3).equals(residentId))
                {
                    onlyUserInfo.add(allUserInfo.get(p));
                    q++;
                }
            }
        }
       
        return onlyUserInfo;
    }

    private ArrayList<ArrayList<String>> allUserDataInfo(String textFile) throws FileNotFoundException 
    {
        File file = new File(textFile);
        ArrayList<ArrayList<String>> allUserInfo = new ArrayList<>();
        if (file.exists()) {
            Scanner sc = new Scanner(file);
            String oneUserInfo; 
            String[] itemArray;
            ArrayList<String> itemArrayList;
            allUserInfo = new ArrayList<>();
            while (sc.hasNextLine()) { 
                oneUserInfo = sc.nextLine().trim(); 
                itemArray = oneUserInfo.split(","); 
                itemArrayList = new ArrayList<>(Arrays.asList(itemArray));
                allUserInfo.add(itemArrayList);
            }
        }
        
        return allUserInfo;
    }
    
    
    private void removeSelected(String part)
    {
        try {
            String fileName = "src/main/java/com/mycompany/textFile/FacilityBooking.txt";
            ArrayList<ArrayList<String>> userData = allUserDataInfo(fileName);
            if(part.equals("upper"))
            {
                for(int j=0;j<userData.size();j++)
                {
                    if(userData.get(j).get(3).equals(residentId)
                            && userData.get(j).get(1).equals(facilityIdTxt1.getText())
                            && userData.get(j).get(4).equals(bookDateTxt1.getText())
                            && userData.get(j).get(5).equals(bookTimeTxt1.getText()))
                    {
                        userData.remove(j);
                        break;
                    }
                }
            }else if(part.equals("bottom"))
            {
                for(int j=0;j<userData.size();j++)
                {
                    if(userData.get(j).get(3).equals(residentId)
                            && userData.get(j).get(1).equals(facilityIdTxt2.getText())
                            && userData.get(j).get(4).equals(bookDateTxt2.getText())
                            && userData.get(j).get(5).equals(bookTimeTxt2.getText()))
                    {
                        userData.remove(j);
                        break;
                    }
                }
            }
            
            File bookingFile = new File(fileName);
            FileWriter fw = new FileWriter(bookingFile);
            BufferedWriter bw = new BufferedWriter(fw);
            for (int j=0; j<userData.size(); j++) 
            {
                ArrayList<String>item = userData.get(j);
                for(int k=0; k<item.size(); k++)
                {
                    if(k == item.size()-1)
                    {
                       bw.write(item.get(k));
                    }else{
                       bw.write(item.get(k)+",");
                    }
                }
                bw.write("\n");
            }
            bw.close();
            
        } catch (IOException ex) {
            Logger.getLogger(FacilityBooking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
