/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.adminExecutive;

import java.io.FileNotFoundException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jun Ming
 */
public class adminExecUnitAddEditFrame extends javax.swing.JFrame {

    /**
     * Creates new form adminExecUnitAddEditFrame
     */
    public adminExecUnitAddEditFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        unitIdLabel = new javax.swing.JLabel();
        unitNumberLabel = new javax.swing.JLabel();
        addEditBtn = new javax.swing.JButton();
        unitIdField = new javax.swing.JTextField();
        unitLocationComboBox = new javax.swing.JComboBox<>();
        unitLocationLabel = new javax.swing.JLabel();
        unitNumberField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setForeground(new java.awt.Color(0, 0, 0));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        unitIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        unitIdLabel.setForeground(new java.awt.Color(0, 0, 0));
        unitIdLabel.setText("Unit ID");

        unitNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        unitNumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        unitNumberLabel.setText("Unit Number");

        addEditBtn.setBackground(new java.awt.Color(255, 255, 255));
        addEditBtn.setForeground(new java.awt.Color(0, 0, 0));
        addEditBtn.setText("UPDATE/ADD");
        addEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEditBtnActionPerformed(evt);
            }
        });

        unitIdField.setBackground(new java.awt.Color(255, 255, 255));
        unitIdField.setEnabled(false);
        unitIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitIdFieldActionPerformed(evt);
            }
        });

        unitLocationComboBox.setBackground(new java.awt.Color(255, 255, 255));
        unitLocationComboBox.setForeground(new java.awt.Color(0, 0, 0));
        unitLocationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitLocationComboBoxActionPerformed(evt);
            }
        });

        unitLocationLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        unitLocationLabel.setForeground(new java.awt.Color(0, 0, 0));
        unitLocationLabel.setText("Unit Location");

        unitNumberField.setBackground(new java.awt.Color(255, 255, 255));
        unitNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitNumberFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(unitNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                .addComponent(unitIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(unitLocationLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(unitLocationComboBox, 0, 234, Short.MAX_VALUE)
                            .addComponent(unitIdField)
                            .addComponent(unitNumberField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(addEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitIdLabel)
                    .addComponent(unitIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitNumberLabel)
                    .addComponent(unitNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitLocationLabel)
                    .addComponent(unitLocationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(addEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        adminExecUnitManageFrame unitPage = new adminExecUnitManageFrame();
        unitPage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        unitPage.pack();
        unitPage.setResizable(false);
        unitPage.setLocationRelativeTo(null);
        unitPage.setVisible(true);
        unitPage.backButtonToggle();
        unitPage.setUnitData();
    }//GEN-LAST:event_backBtnActionPerformed

    private void addEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEditBtnActionPerformed
        // TODO add your handling code here:
        if(addEditDetector=="edit"){
            if((unitIdField.getText()).equals("")  ||(unitNumberField.getText()).equals("")||((String)unitLocationComboBox.getSelectedItem()).equals("") ){
                JOptionPane.showMessageDialog(null, "Enter all field", "Warning", JOptionPane.ERROR_MESSAGE);
            }else{
                adminExecutive main = new adminExecutive();
                adminExecutive.adminExecutiveMethod mainInner = main.new adminExecutiveMethod();
                ArrayList<String> dataList = new ArrayList<String>();
                dataList.add(unitIdField.getText());
                dataList.add(unitNumberField.getText());
                dataList.add((String)unitLocationComboBox.getSelectedItem());
                dataList.add("Available");
                mainInner.addEditUnit(dataList, "Unit","Unit.txt","edit");
            }
        }else if(addEditDetector=="add"){
            if((unitNumberField.getText()).equals("")||((String)unitLocationComboBox.getSelectedItem()).equals("") ){
                JOptionPane.showMessageDialog(null, "Enter all field", "Warning", JOptionPane.ERROR_MESSAGE);
            }else{
                adminExecutive main = new adminExecutive();
                adminExecutive.adminExecutiveMethod mainInner = main.new adminExecutiveMethod();
                unit unitClass = new unit();
                ArrayList<String> dataList = new ArrayList<String>();

                unitClass.getIncreasedID("Unit.txt","Unit");
                dataList.add(unitClass.getUnitId());
                dataList.add(unitNumberField.getText());
                dataList.add((String)unitLocationComboBox.getSelectedItem());
                dataList.add("Available");
                mainInner.addEditUnit(dataList, "Unit","Unit.txt","add");
                unitNumberField.setText("");
            }
        }
    }//GEN-LAST:event_addEditBtnActionPerformed

    private void unitIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitIdFieldActionPerformed

    private void unitLocationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitLocationComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitLocationComboBoxActionPerformed

    private void unitNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitNumberFieldActionPerformed

    private String addEditDetector;
    private String fileType="Unit.txt";
    private String userType="Unit";
     
    public void addEditDetect(String functionType,String id) throws FileNotFoundException {
        if(functionType=="edit"){
            this.addEditDetector="edit";
            unit unitClass = new unit();
            unitClass.chooseTxtFile("Unit");
            unitClass.getDataViewSingle(id, fileType,userType);
            addEditBtn.setText("Update");
            unitIdField.setText(unitClass.getUnitId());
            unitNumberField.setText(unitClass.getUnitNumber());
            unitLocationComboBox.addItem("Block A");
            unitLocationComboBox.addItem("Block B");
            unitLocationComboBox.addItem("Block C");
            unitLocationComboBox.addItem("Block D");
            unitLocationComboBox.setSelectedItem(unitClass.getUnitLocation());
            System.out.println(unitClass.getUnitLocation());
        }else if (functionType=="add"){
            this.addEditDetector="add";
            addEditBtn.setText("Add");
            unitIdField.setVisible(false);
            unitIdLabel.setVisible(false);
            unitLocationComboBox.addItem("Block A");
            unitLocationComboBox.addItem("Block B");
            unitLocationComboBox.addItem("Block C");
            unitLocationComboBox.addItem("Block D");
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminExecUnitAddEditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminExecUnitAddEditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminExecUnitAddEditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminExecUnitAddEditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminExecUnitAddEditFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEditBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField unitIdField;
    private javax.swing.JLabel unitIdLabel;
    private javax.swing.JComboBox<String> unitLocationComboBox;
    private javax.swing.JLabel unitLocationLabel;
    private javax.swing.JTextField unitNumberField;
    private javax.swing.JLabel unitNumberLabel;
    // End of variables declaration//GEN-END:variables
}
