/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.adminExecutive;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jun Ming
 */
public class adminExecComplaintAddEditFrame extends javax.swing.JFrame {

    /**
     * Creates new form adminExecComplaintAddEditFrame
     */
    public adminExecComplaintAddEditFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        complaintIdLabel = new javax.swing.JLabel();
        complaintDetailLabel = new javax.swing.JLabel();
        complaintFromLabel = new javax.swing.JLabel();
        addEditBtn = new javax.swing.JButton();
        complaintIdField = new javax.swing.JTextField();
        userComboBox = new javax.swing.JComboBox<>();
        complaintReplyLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        complaintDetailField = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        complaintReplyField = new javax.swing.JTextArea();
        complaintUserTypeLabel1 = new javax.swing.JLabel();
        userTypeComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setForeground(new java.awt.Color(0, 0, 0));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        complaintIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        complaintIdLabel.setForeground(new java.awt.Color(0, 0, 0));
        complaintIdLabel.setText("Complaint ID");

        complaintDetailLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        complaintDetailLabel.setForeground(new java.awt.Color(0, 0, 0));
        complaintDetailLabel.setText("Complaint details");

        complaintFromLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        complaintFromLabel.setForeground(new java.awt.Color(0, 0, 0));
        complaintFromLabel.setText("From");

        addEditBtn.setBackground(new java.awt.Color(255, 255, 255));
        addEditBtn.setForeground(new java.awt.Color(0, 0, 0));
        addEditBtn.setText("UPDATE/ADD");
        addEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEditBtnActionPerformed(evt);
            }
        });

        complaintIdField.setBackground(new java.awt.Color(255, 255, 255));
        complaintIdField.setEnabled(false);
        complaintIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complaintIdFieldActionPerformed(evt);
            }
        });

        userComboBox.setBackground(new java.awt.Color(255, 255, 255));
        userComboBox.setForeground(new java.awt.Color(0, 0, 0));
        userComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userComboBoxActionPerformed(evt);
            }
        });

        complaintReplyLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        complaintReplyLabel.setForeground(new java.awt.Color(0, 0, 0));
        complaintReplyLabel.setText("Complaint Reply");

        complaintDetailField.setBackground(new java.awt.Color(255, 255, 255));
        complaintDetailField.setColumns(20);
        complaintDetailField.setRows(5);
        jScrollPane1.setViewportView(complaintDetailField);

        complaintReplyField.setBackground(new java.awt.Color(255, 255, 255));
        complaintReplyField.setColumns(20);
        complaintReplyField.setRows(5);
        jScrollPane2.setViewportView(complaintReplyField);

        complaintUserTypeLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        complaintUserTypeLabel1.setForeground(new java.awt.Color(0, 0, 0));
        complaintUserTypeLabel1.setText("Type");

        userTypeComboBox.setBackground(new java.awt.Color(255, 255, 255));
        userTypeComboBox.setForeground(new java.awt.Color(0, 0, 0));
        userTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTypeComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(complaintDetailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                .addComponent(complaintIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(complaintFromLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(complaintUserTypeLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(complaintReplyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addComponent(complaintIdField)
                            .addComponent(userTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(addEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(complaintIdLabel)
                    .addComponent(complaintIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(complaintDetailLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(complaintReplyLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(complaintUserTypeLabel1)
                    .addComponent(userTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(complaintFromLabel))
                .addGap(30, 30, 30)
                .addComponent(addEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        adminExecComplaintManageFrame complaintPage = new adminExecComplaintManageFrame();
        complaintPage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        complaintPage.pack();
        complaintPage.setResizable(false);
        complaintPage.setLocationRelativeTo(null);
        complaintPage.setVisible(true);
        complaintPage.backButtonToggle();
        complaintPage.setComplaintData();
    }//GEN-LAST:event_backBtnActionPerformed

    private void addEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEditBtnActionPerformed
        // TODO add your handling code here:
        if(addEditDetector=="edit"){
            if((complaintDetailField.getText()).equals("")  ||((String)userComboBox.getSelectedItem()).equals("") ){
                JOptionPane.showMessageDialog(null, "Enter all field", "Warning", JOptionPane.ERROR_MESSAGE);
            }else{
                adminExecutive main = new adminExecutive();
                adminExecutive.adminExecutiveMethod mainInner = main.new adminExecutiveMethod();
                ArrayList<String> dataList = new ArrayList<String>();
                dataList.add(complaintIdField.getText());
                dataList.add(complaintDetailField.getText());
                dataList.add(complaintReplyField.getText());
                dataList.add((String)userComboBox.getSelectedItem());
                mainInner.addEditComplaint(dataList, "Complaint","Complaint.txt","edit");
            }
        }else if(addEditDetector=="add"){
            if((complaintDetailField.getText()).equals("") ||((String)userComboBox.getSelectedItem()).equals("") ){
                JOptionPane.showMessageDialog(null, "Enter all field", "Warning", JOptionPane.ERROR_MESSAGE);
            }else{
                adminExecutive main = new adminExecutive();
                adminExecutive.adminExecutiveMethod mainInner = main.new adminExecutiveMethod();
                complaint complaintClass = new complaint();
                ArrayList<String> dataList = new ArrayList<String>();
                
                complaintClass.getIncreasedID("Complaint.txt","Complaint");
                dataList.add(complaintClass.getComplaintId());
                dataList.add(complaintDetailField.getText());
                dataList.add("-");
                dataList.add((String)userComboBox.getSelectedItem());
                mainInner.addEditComplaint(dataList, "Complaint","Complaint.txt","add");
                complaintDetailField.setText("");
                complaintReplyField.setText("");
            }
        }
    }//GEN-LAST:event_addEditBtnActionPerformed

    private void complaintIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complaintIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complaintIdFieldActionPerformed

    private void userComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userComboBoxActionPerformed

    private void userTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTypeComboBoxActionPerformed
        // TODO add your handling code here:
        complaint complaintClass = new complaint();
        complaint.complaintMethod mainInner = complaintClass.new complaintMethod();
        if(((String)userTypeComboBox.getSelectedItem()).equals("Vendor")){
                userComboBox.removeAllItems();
            try {
                mainInner.getDropDownData("VendorProfile.txt","Complaint");
            } catch (FileNotFoundException ex) {

            }
                int i=0;
                for (String x : complaintClass.getDropDownData()) {
                    userComboBox.addItem((complaintClass.getDropDownData()).get(i));
                    i++;
                }   
        }
            else if(((String)userTypeComboBox.getSelectedItem()).equals("Resident")){
                userComboBox.removeAllItems();
            try {
                mainInner.getDropDownData("residentProfile.txt","Complaint");
            } catch (FileNotFoundException ex) {

            }
                int i=0;
                for (String x : complaintClass.getDropDownData()) {
                    userComboBox.addItem((complaintClass.getDropDownData()).get(i));
                    i++;
                } 
        }
    }//GEN-LAST:event_userTypeComboBoxActionPerformed

    private String addEditDetector;
    private String fileType="Complaint.txt";
    private String userType="Complaint";
    
    public void addEditDetect(String functionType,String id) throws FileNotFoundException {
        if(functionType=="edit"){
            this.addEditDetector="edit";
            complaint complaintClass = new complaint();
            complaintClass.chooseTxtFile("Complaint");
            complaintClass.getDataViewSingle(id, fileType,userType);
            complaint.complaintMethod mainInner = complaintClass.new complaintMethod();
            
            addEditBtn.setText("Update");
            complaintIdField.setText(complaintClass.getComplaintId());
            complaintDetailField.setText(complaintClass.getComplaintDescription());
            complaintReplyField.setText(complaintClass.getComplaintReply());
            System.out.println((complaintClass.getUserId()).substring(0,1));
            if((complaintClass.getUserId()).substring(0,1).equals("V")){
                userTypeComboBox.addItem("Vendor");
                userTypeComboBox.addItem("Resident");
                mainInner.getDropDownData("VendorProfile.txt","Complaint");
            }else if ((complaintClass.getUserId()).substring(0,1).equals("R")){
                userTypeComboBox.addItem("Resident");
                userTypeComboBox.addItem("Vendor");
                mainInner.getDropDownData("residentProfile.txt","Complaint");
            }
            int i=0;
            for (String x : complaintClass.getDropDownData()) {
                userComboBox.addItem((complaintClass.getDropDownData()).get(i));
                i++;
            }
            userComboBox.setSelectedItem(complaintClass.getUserId());
        }else if (functionType=="add"){
            this.addEditDetector="add";
            addEditBtn.setText("Add");
            complaintIdField.setVisible(false);
            complaintIdLabel.setVisible(false);
            complaintReplyField.setEnabled(false);
            complaint complaintClass = new complaint();
            complaint.complaintMethod mainInner = complaintClass.new complaintMethod();
            userTypeComboBox.addItem("Vendor");
            userTypeComboBox.addItem("Resident");
            if(((String)userTypeComboBox.getSelectedItem()).equals("Vendor")){
                userComboBox.removeAllItems();
                mainInner.getDropDownData("VendorProfile.txt","Complaint");
                int i=0;
                for (String x : complaintClass.getDropDownData()) {
                    userComboBox.addItem((complaintClass.getDropDownData()).get(i));
                    i++;
                }   
        }
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminExecComplaintAddEditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminExecComplaintAddEditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminExecComplaintAddEditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminExecComplaintAddEditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminExecComplaintAddEditFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEditBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextArea complaintDetailField;
    private javax.swing.JLabel complaintDetailLabel;
    private javax.swing.JLabel complaintFromLabel;
    private javax.swing.JTextField complaintIdField;
    private javax.swing.JLabel complaintIdLabel;
    private javax.swing.JTextArea complaintReplyField;
    private javax.swing.JLabel complaintReplyLabel;
    private javax.swing.JLabel complaintUserTypeLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> userComboBox;
    private javax.swing.JComboBox<String> userTypeComboBox;
    // End of variables declaration//GEN-END:variables
}
