/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.AccExecutive;

import com.mycompany.AccExecutive.AccExecMain;
import com.mycompany.mavenproject1.BusManBudgetPlanningManage;
import com.mycompany.mavenproject1.BusManUserManageOption;

import java.awt.BorderLayout;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.BorderFactory;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.BorderFactory;
import javax.swing.border.EmptyBorder;

import com.mycompany.AccExecutive.ModelReceipt;
import java.io.*; 

/**
 *
 * @author user
 */
public class AccExecReceiptManage extends javax.swing.JFrame {

    String userId;

    /**
     * Creates new form AccExecReceiptManage
     */
    public AccExecReceiptManage() {
        initComponents();
    }
    public AccExecReceiptManage(String userId) {
        this();
        this.userId = userId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        DataPanel = new JPanel();
        HeaderPanel = new JPanel();
        // NavigationPanel = new JPanel();

        OptionAccExecReceiptManage = new javax.swing.JButton();
        AddNewAccExecReceiptManage = new javax.swing.JButton();
        // BackAccExecReceiptManage = new javax.swing.JButton();
        // NextAccExecReceiptManage = new javax.swing.JButton();

        OptionAccExecReceiptManage.setBackground(new java.awt.Color(204, 204, 204));
        OptionAccExecReceiptManage.setForeground(new java.awt.Color(0, 0, 0));
        OptionAccExecReceiptManage.setText("Back");
        OptionAccExecReceiptManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispose();
                AccExecMain nextFrame = new AccExecMain();
                nextFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                nextFrame.pack();
                nextFrame.setResizable(false);
                nextFrame.setLocationRelativeTo(null);
                nextFrame.setVisible(true);
            }
        });

        AddNewAccExecReceiptManage.setBackground(new java.awt.Color(204, 204, 204));
        AddNewAccExecReceiptManage.setForeground(new java.awt.Color(0, 0, 0));
        AddNewAccExecReceiptManage.setText("Add New");
        AddNewAccExecReceiptManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // AddNewAccExecReceiptManageActionPerformed(evt);
                changeFrame(new ModelReceipt());
            }
        });

        // BackAccExecReceiptManage.setBackground(new java.awt.Color(204, 204, 204));
        // BackAccExecReceiptManage.setForeground(new java.awt.Color(0, 0, 0));
        // BackAccExecReceiptManage.setText("Back");
        // BackAccExecReceiptManage.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         // BackAccExecReceiptManage2ActionPerformed(evt);
        //     }
        // });

        // NextAccExecReceiptManage.setBackground(new java.awt.Color(204, 204, 204));
        // NextAccExecReceiptManage.setForeground(new java.awt.Color(0, 0, 0));
        // NextAccExecReceiptManage.setText("Next");
        // NextAccExecReceiptManage.addActionListener(new java.awt.event.ActionListener() {
        //     public void actionPerformed(java.awt.event.ActionEvent evt) {
        //         // NextAccExecReceiptManageActionPerformed(evt);
        //     }
        // });

        HeaderPanel.setBackground(new java.awt.Color(254, 204, 204));
        // NavigationPanel.setBackground(new java.awt.Color(254, 204, 254));

        add(HeaderPanel, BorderLayout.PAGE_START);
        HeaderPanel.add(OptionAccExecReceiptManage, BorderLayout.LINE_START);
        HeaderPanel.add(AddNewAccExecReceiptManage, BorderLayout.LINE_END);

        add(new JScrollPane(DataPanel));
        DataPanel.setSize(500, 450);
        DataPanel.setLayout(new BoxLayout(DataPanel, BoxLayout.Y_AXIS));

        // add(NavigationPanel, BorderLayout.PAGE_END);
        // NavigationPanel.add(BackAccExecReceiptManage, BorderLayout.LINE_START);
        // NavigationPanel.add(NextAccExecReceiptManage, BorderLayout.LINE_END);

        String fileName = "./com/mycompany/textFile/ReceiptContent.txt";
        try (BufferedReader br = new BufferedReader(new FileReader(fileName))) {
            String line;
            while ((line = br.readLine()) != null) {
                newReceipt(line);
            }
        } catch (IOException e) {
            System.err.println("Error reading file: " + e.getMessage());
        }

        DataPanel.setBackground(Color.BLUE);
        setSize(500, 450);
        // pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeFrame(ModelReceipt receipt) {
        dispose();
        AccExecReceiptView nextFrame = new AccExecReceiptView(receipt);
        nextFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // nextFrame.pack();
        // nextFrame.setResizable(false);
        nextFrame.setLocationRelativeTo(null);
        nextFrame.setVisible(true);
    }

    private void newReceipt(String line) {
        ModelReceipt receipt = new ModelReceipt(line);
        JPanel receiptPanel = new JPanel();

        receiptPanel.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(Color.black), new EmptyBorder(0,40,0,0)));
        // receiptPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        // receiptPanel.setBorder();
        receiptPanel.setPreferredSize(new Dimension(300, 180));
        receiptPanel.setLayout(new GridBagLayout());

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;


        receiptPanel.add(new JLabel("Receipt ID: "), gbc);
        gbc.gridy++;
        receiptPanel.add(new JLabel("User ID: "), gbc);
        gbc.gridy++;
        receiptPanel.add(new JLabel("Description: "), gbc);
        gbc.gridy++;
        receiptPanel.add(new JLabel("Paid Amount: "), gbc);
        gbc.gridy++;
        receiptPanel.add(new JLabel("Paid Date: "), gbc);
        gbc.gridy++;
        receiptPanel.add(new JLabel("Date Issued: "), gbc);

        gbc.gridx = 1;
        gbc.gridy = 1;
        receiptPanel.add(new JLabel(receipt.getReceiptId()), gbc);
        gbc.gridy++;
        receiptPanel.add(new JLabel(receipt.getUserId()), gbc);
        gbc.gridy++;
        receiptPanel.add(new JLabel(receipt.getDescription()), gbc);
        gbc.gridy++;
        receiptPanel.add(new JLabel(receipt.getPaidAmount()), gbc);
        gbc.gridy++;
        receiptPanel.add(new JLabel(receipt.getPaidDate()), gbc);
        gbc.gridy++;
        receiptPanel.add(new JLabel(receipt.getDateIssued()), gbc);

        JButton viewBtn = new JButton("View Details");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeFrame(receipt);
            }
        });

        JButton removeBtn = new JButton("Remove Details");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

                String fileName = "./com/mycompany/textFile/ReceiptContent.txt";
                String lineToRemove = receipt.toString();

                try (BufferedReader br = new BufferedReader(new FileReader(fileName))) {
                    StringBuilder sb = new StringBuilder();
                    String line;
                    while ((line = br.readLine()) != null) {
                        if (!line.trim().equals(lineToRemove)) {
                            sb.append(line).append("\n");
                        }
                    }
                    try (BufferedWriter bw = new BufferedWriter(new FileWriter(fileName))) {
                        bw.write(sb.toString());
                    } catch (IOException e) {
                        System.err.println("Error writing to file: " + e.getMessage());
                    }
                } catch (IOException e) {
                    System.err.println("Error reading file: " + e.getMessage());
                }

                System.out.println("REMOVED! "+receipt);
                DataPanel.remove(receiptPanel);
                invalidate();
                validate();
                repaint();
            }
        });

        gbc.gridx = 2;
        gbc.gridy = 1;
        receiptPanel.add(viewBtn, gbc);
        gbc.gridy = 2;
        receiptPanel.add(removeBtn, gbc);

        DataPanel.add(receiptPanel, BorderLayout.CENTER);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccExecReceiptManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccExecReceiptManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccExecReceiptManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccExecReceiptManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccExecReceiptManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataPanel;
    private javax.swing.JPanel HeaderPanel;
    // private javax.swing.JPanel NavigationPanel;

    private javax.swing.JButton AddNewAccExecReceiptManage;
    private javax.swing.JButton OptionAccExecReceiptManage;
    // private javax.swing.JButton BackAccExecReceiptManage;
    // private javax.swing.JButton NextAccExecReceiptManage;

    // End of variables declaration//GEN-END:variables
}
