/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.employee;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hoiyi
 */
public class guardCheckPointViewFrame extends javax.swing.JFrame {

    static String idGet;
    
    public guardCheckPointViewFrame(String id) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        idGet = id;
        noDataLabel.setVisible(false);
        displayData();
        createTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        topLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        checkPointRecordTable = new javax.swing.JTable();
        noDataLabel = new javax.swing.JLabel();
        checkInBtn = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        idTxt = new javax.swing.JLabel();
        blockLabel = new javax.swing.JLabel();
        blockTxt = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        timeTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(233, 233, 233));
        jPanel1.setPreferredSize(new java.awt.Dimension(566, 600));

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setForeground(new java.awt.Color(0, 0, 0));
        backBtn.setText("Back");
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        topLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        topLabel.setForeground(new java.awt.Color(0, 0, 0));
        topLabel.setText("CHECKPOINT");

        checkPointRecordTable.setBackground(new java.awt.Color(233, 233, 233));
        checkPointRecordTable.setForeground(new java.awt.Color(0, 0, 0));
        checkPointRecordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(checkPointRecordTable);

        noDataLabel.setBackground(new java.awt.Color(233, 233, 233));
        noDataLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        noDataLabel.setForeground(new java.awt.Color(0, 0, 0));
        noDataLabel.setText("No Record");

        checkInBtn.setBackground(new java.awt.Color(255, 255, 255));
        checkInBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkInBtn.setForeground(new java.awt.Color(0, 0, 0));
        checkInBtn.setText("CHECK IN");
        checkInBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInBtnActionPerformed(evt);
            }
        });

        idLabel.setBackground(new java.awt.Color(233, 233, 233));
        idLabel.setForeground(new java.awt.Color(0, 0, 0));
        idLabel.setText("Guard ID :");

        idTxt.setBackground(new java.awt.Color(233, 233, 233));
        idTxt.setForeground(new java.awt.Color(0, 0, 0));
        idTxt.setText("E1");

        blockLabel.setBackground(new java.awt.Color(233, 233, 233));
        blockLabel.setForeground(new java.awt.Color(0, 0, 0));
        blockLabel.setText("Block Number :");

        blockTxt.setBackground(new java.awt.Color(233, 233, 233));
        blockTxt.setForeground(new java.awt.Color(0, 0, 0));
        blockTxt.setText("Block A");

        timeLabel.setBackground(new java.awt.Color(233, 233, 233));
        timeLabel.setForeground(new java.awt.Color(0, 0, 0));
        timeLabel.setText("Checkpoint Time :");

        timeTxt.setBackground(new java.awt.Color(233, 233, 233));
        timeTxt.setForeground(new java.awt.Color(0, 0, 0));
        timeTxt.setText("0800");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(noDataLabel)
                .addGap(17, 17, 17))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(checkInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(blockLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blockTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(topLabel)))
                .addGap(0, 160, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(85, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(105, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(topLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idTxt))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blockLabel)
                    .addComponent(blockTxt))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLabel)
                    .addComponent(timeTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(noDataLabel)
                .addGap(110, 110, 110)
                .addComponent(checkInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(236, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(60, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        guardMenuFrame menu = new guardMenuFrame(idGet);
        menu.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void checkInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInBtnActionPerformed
        this.dispose();
        guardCheckPointAddFrame add = new guardCheckPointAddFrame(idGet);
        add.setVisible(true);
    }//GEN-LAST:event_checkInBtnActionPerformed

    private void createTable()
    {
        checkpointRecord main = new checkpointRecord();
        main.setUserId(idGet);
        main.displayDataViewOwn(0, "", "checkpointRecord", "CheckpointRecord");
        if(main.getCheckPointRecordID() != null)
        {
            int totalRow = main.getTotalLine();
            
            String[] tableHeader = {"Block Number", "Check Point Date", "Check Point Time"};
            DefaultTableModel model = (DefaultTableModel) checkPointRecordTable.getModel();
            model.setColumnIdentifiers(tableHeader);
            
            for(int i=0; i<totalRow; i++)
            {
                main.displayDataViewOwn(i, "", "checkpointRecord", "CheckpointRecord");
                String[] dataRow = {main.getBlockNumber(), main.getCheckPointRecordDate(), main.getCheckPointRecordTime()};
                model.addRow(dataRow);
            }
                
        }else{
            noDataLabel.setVisible(true);
        }
        
    }
    
    private void displayData()
    {
        idTxt.setText(idGet);
        checkpoint checkpointClass = new checkpoint();
        checkpointClass.setUserId(idGet);
        checkpointClass.displayDataViewOwn(0, "", "checkpoint", "Checkpoint");
        if(checkpointClass.getCheckpointId() != null)
        {
            blockTxt.setText(checkpointClass.getBlockNumber());
            timeTxt.setText(checkpointClass.getCheckpointTime());
            
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guardCheckPointViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guardCheckPointViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guardCheckPointViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guardCheckPointViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guardCheckPointViewFrame(idGet).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel blockLabel;
    private javax.swing.JLabel blockTxt;
    private javax.swing.JButton checkInBtn;
    private javax.swing.JTable checkPointRecordTable;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idTxt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel noDataLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel timeTxt;
    private javax.swing.JLabel topLabel;
    // End of variables declaration//GEN-END:variables
}
