/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.buildingManager;

import java.io.FileNotFoundException;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author Jun Ming
 */
public class buildingManBudgetAddEditFrame extends javax.swing.JFrame {

    /**
     * Creates new form buildingManBudgetAddEditFrame
     */
    public buildingManBudgetAddEditFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        projectIdLabel = new javax.swing.JLabel();
        projectNameLabel = new javax.swing.JLabel();
        projectBudgetLabel = new javax.swing.JLabel();
        projectStartDateLabel = new javax.swing.JLabel();
        projectEndDateLabel = new javax.swing.JLabel();
        addEditBtn = new javax.swing.JButton();
        projectNameField = new javax.swing.JTextField();
        projectBudgetField = new javax.swing.JTextField();
        projectStartDateField = new javax.swing.JTextField();
        projectEndDateField = new javax.swing.JTextField();
        projectIdField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setForeground(new java.awt.Color(0, 0, 0));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        projectIdLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        projectIdLabel.setForeground(new java.awt.Color(0, 0, 0));
        projectIdLabel.setText("Project ID");

        projectNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        projectNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        projectNameLabel.setText("Project Name");

        projectBudgetLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        projectBudgetLabel.setForeground(new java.awt.Color(0, 0, 0));
        projectBudgetLabel.setText("Project Budget");

        projectStartDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        projectStartDateLabel.setForeground(new java.awt.Color(0, 0, 0));
        projectStartDateLabel.setText("Project Start Date ");

        projectEndDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        projectEndDateLabel.setForeground(new java.awt.Color(0, 0, 0));
        projectEndDateLabel.setText("Project End Date ");

        addEditBtn.setBackground(new java.awt.Color(255, 255, 255));
        addEditBtn.setForeground(new java.awt.Color(0, 0, 0));
        addEditBtn.setText("UPDATE/ADD");
        addEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEditBtnActionPerformed(evt);
            }
        });

        projectNameField.setBackground(new java.awt.Color(255, 255, 255));
        projectNameField.setForeground(new java.awt.Color(0, 0, 0));

        projectBudgetField.setBackground(new java.awt.Color(255, 255, 255));
        projectBudgetField.setForeground(new java.awt.Color(0, 0, 0));

        projectStartDateField.setBackground(new java.awt.Color(255, 255, 255));
        projectStartDateField.setForeground(new java.awt.Color(0, 0, 0));

        projectEndDateField.setBackground(new java.awt.Color(255, 255, 255));
        projectEndDateField.setForeground(new java.awt.Color(0, 0, 0));

        projectIdField.setBackground(new java.awt.Color(255, 255, 255));
        projectIdField.setEnabled(false);
        projectIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectIdFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(projectNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(projectIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(projectBudgetLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(projectStartDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(projectEndDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(projectNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projectBudgetField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projectStartDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projectEndDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projectIdField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(addEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectIdLabel)
                    .addComponent(projectIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectNameLabel)
                    .addComponent(projectNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectBudgetLabel)
                    .addComponent(projectBudgetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectStartDateLabel)
                    .addComponent(projectStartDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectEndDateLabel)
                    .addComponent(projectEndDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(addEditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
//        if(!projectIdField.isVisible()){
        this.dispose();
        buildingManBudgetManageFrame budgetManage = new buildingManBudgetManageFrame();
        budgetManage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        budgetManage.pack();
        budgetManage.setResizable(false);
        budgetManage.setLocationRelativeTo(null);
        budgetManage.setVisible(true);
        budgetManage.backButtonToggle();
        //Run Method set UserType and Data
        budgetManage.setBudgetPlanningData();
//        }else{
//            this.dispose();
//            BusManBudgetPlanningView budgetView = new BusManBudgetPlanningView();
//            budgetView.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//            budgetView.pack();
//            budgetView.setResizable(false);
//            budgetView.setLocationRelativeTo(null);
//            budgetView.setVisible(true);
//            try {
//                budgetView.setDataViewSingle(projectIdField.getText());
//            } catch (FileNotFoundException ex) {
//            }
//        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void addEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEditBtnActionPerformed
        // TODO add your handling code here:
        if(addEditDetector=="edit"){
            budgetPlanning budget = new budgetPlanning();
            ArrayList<String> dataList = new ArrayList<String>();
            dataList.add(projectIdField.getText());
            dataList.add(projectNameField.getText());
            dataList.add(projectBudgetField.getText());
            dataList.add(projectStartDateField.getText());
            dataList.add(projectEndDateField.getText());
            budget.editOrAddData(dataList, "budget","BudgetPlanning.txt","edit");
        }else if(addEditDetector=="add"){
            budgetPlanning budget = new budgetPlanning();
            ArrayList<String> dataList = new ArrayList<String>();
            budget.getIncreasedID("BudgetPlanning.txt","budget");
            dataList.add(budget.getBudgetId());
            dataList.add(projectNameField.getText());
            dataList.add(projectBudgetField.getText());
            dataList.add(projectStartDateField.getText());
            dataList.add(projectEndDateField.getText());
            budget.editOrAddData(dataList, "budget","BudgetPlanning.txt","add");
        }
    }//GEN-LAST:event_addEditBtnActionPerformed

    private void projectIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectIdFieldActionPerformed

    
    private String addEditDetector;
    
    
    public void addEditDetect(String functionType,String id) throws FileNotFoundException{
        if(functionType=="edit"){
            this.addEditDetector="edit";
            budgetPlanning budgetClass = new budgetPlanning();
            budgetClass.getDataViewSingle(id, "BudgetPlanning.txt","budget");
            addEditBtn.setText("Update");
            projectIdField.setText(budgetClass.getBudgetId());
            projectNameField.setText(budgetClass.getBudgetProjectName());
            projectBudgetField.setText(budgetClass.getBudgetProjectBudget());
            projectStartDateField.setText(budgetClass.getBudgetProjectStartDate());
            projectEndDateField.setText(budgetClass.getBudgetProjectEndDate());
        }else if (functionType=="add"){
            this.addEditDetector="add";
            addEditBtn.setText("Add");
            projectIdField.setVisible(false);
            projectIdLabel.setVisible(false);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buildingManBudgetAddEditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buildingManBudgetAddEditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buildingManBudgetAddEditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buildingManBudgetAddEditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buildingManBudgetAddEditFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEditBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField projectBudgetField;
    private javax.swing.JLabel projectBudgetLabel;
    private javax.swing.JTextField projectEndDateField;
    private javax.swing.JLabel projectEndDateLabel;
    private javax.swing.JTextField projectIdField;
    private javax.swing.JLabel projectIdLabel;
    private javax.swing.JTextField projectNameField;
    private javax.swing.JLabel projectNameLabel;
    private javax.swing.JTextField projectStartDateField;
    private javax.swing.JLabel projectStartDateLabel;
    // End of variables declaration//GEN-END:variables
}
